### ISSUE TITLE
AutoLinking not working

### ISSUE THREAD

**Issue by iujisato** [mateoguzmana/react-native-zendesk-unified#1]
AutoLink feature doesnt seem to be working, if I try to add the package on my project pods are not installed.

Also on your example app, there's no line referencing the library as a JS dependency, so it's probably outdated or linked through a different method

**Comment by mateoguzmana** [comment]
Hey there @iujisato, thanks for flagging the issue.

Do you mind sharing your react-native version or somewhere I can reproduce it?

I have this example app which you can use to try it out, you can see the package installed here: https://github.com/mateoguzmana/ZendeskDemo/blob/main/package.json#L63

**Comment by iujisato** [comment]
Hey @mateoguzmana sorry for the late response!

I'm using RN 0.63.5

**Comment by mateoguzmana** [comment]
Hey there, I haven't tested this package in an old React Native version. This library is fairly new so it can't guarantee supporting versions which are a bit far behind.

The latest stable React Native version as of now is 0.73.0. I would suggest updating to a newer version and trying it out again.

I'll update the docs as soon as I know which is the latest version this package supports. Closing this issue for now
