### ISSUE TITLE
I need to change the chat theme for android. 

### ISSUE THREAD

**Issue by sayancitytech** [mateoguzmana/react-native-zendesk-unified#3]
As it is not supported yet.
![Screenshot_1710856248](https://github.com/mateoguzmana/react-native-zendesk-unified/assets/163546851/62b49877-73d0-4daa-b02f-7c9449e3f744)
![Screenshot_1710856256](https://github.com/mateoguzmana/react-native-zendesk-unified/assets/163546851/7066d17c-aa87-4377-9988-eef3b799277e)

**Comment by sayancitytech** [comment]
added  inside styles.xml 
```
<resources>
    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="android:editTextBackground">@drawable/rn_edit_text_material</item>
        <item name="android:textColor">#000000</item>
        <item name="colorPrimary">#990099</item>
        <item name="colorPrimaryDark">#990099</item>
        <item name="colorAccent">#990099</item>
    </style>
</resources>
```

working perfect now

**Comment by mateoguzmana** [comment]
Thanks for sharing @sayancitytech, glad to know it worked for you.

Perhaps we need to update the docs to mention explicitly that the options can be set directly on the Android level. Closing the issue for now
